### ISSUE TITLE
Schreibweise von CreateTable

### ISSUE THREAD

**Issue by xgamerg1rl** [kevgk/Leya#11]
Hey.

leider bekomme ich (egal wie ich ihn formatiere) beim Befehl `leya.createTable` entweder ein -4 (was an der rechte-vergabe liegt) nach dem Umstellen bekomme ich aber immer eine 0 als _error und es wird keine Tabelle bestellt.

Kannst du mir sagen, wie ich den Befehl formatieren muss (am besten direkt mit mehreren Spalten beim erstellen ;)

**Comment by xgamerg1rl** [comment]
Frage hat sich geklärt. 
`leya.createTable("TABELLENNAME","SPALTE1,SPALTE2")`

**Comment by kevgk** [comment]
`leya.createTable("TABELLENNAME","SPALTE1, SPALTE2, SPALTE3")`
