### ISSUE TITLE
leya.countrows Fehler beim auslesen ?

### ISSUE THREAD

**Issue by xgamerg1rl** [kevgk/Leya#12]
Ich bekomme bei dem Befehl `leya.countrows("Mitarbeiter")` leider nur `ï»¿<!--response=""1""-->` zurück...
Habe mir jetzt mit 
`Anzahl_Rows := leya.listRows("Mitarbeiter")`
`Anzahl_Rows := Anzahl_Rows.__affectedRows`
beholfen. Aber des Rätsels Lösung kann da ja nicht sein ;)

**Comment by kevgk** [comment]
Das Problem ist, dass jeder Request ein Object mit den geforderten Daten, aber auch mit Informationen wie __affectedRows und __error, sein muss.

Eine Lösung wäre, die Daten in dem Object unter "data" zu returnen. In diesem Fall etwa so...
```autohotkey
Anzahl_Rows := leya.listRows("Mitarbeiter")
msgbox % Anzahl_Rows.data
```

Dann würde jede Antwort auf ein Request wie folgt aussehen.
`
{
    data,
    __affectedRows,
    __error
}
`

Ich werde darüber nachdenken und ggf. die Tage die API umschreiben.

**Comment by kevgk** [comment]
Das Problem ist jetzt mit V3 gelöst.

/edit:
Ich sollte noch anmerken, dass das Update breaking Changes mit sich bringt. Und jetzt jede Antwort einer Funktion ein Object ist und die Daten unter data liegen. Ausserdem fallen bei __error und __affectedRows die Unterstriche weg.

**Comment by Pillowg1rl** [comment]
Also (als Beispiel) ist jetzt 
`Readout := leya.get("Mitarbeiter",Userloginname,"Vorname")`
`Readout := Readout.Data.Vorname`
`Readout := Readout.error`
//solved (falls jemand eine ähnliche Frage hat)
