### ISSUE TITLE
Readout fehlermeldung bei Zugriff auf Tabelle

### ISSUE THREAD

**Issue by xgamerg1rl** [kevgk/Leya#13]
Kannst du mit den beiden Fehlermeldungen etwas anfangen ? Ich bekomme sie, wenn ich ein Gui aufrufen will, welches Daten aus der MYSQL ausließt... 

![SciTE_cTEml1Mte9](https://user-images.githubusercontent.com/33255960/80369277-4f932b80-888e-11ea-9f33-47c5c3f99650.png)
![SciTE_j5LmUxMUv2](https://user-images.githubusercontent.com/33255960/80369281-502bc200-888e-11ea-8bd8-a8c9595e0dad.png)

**Comment by kevgk** [comment]
Bitte einmal Code dazu posten, am besten direkt hier.

**Comment by xgamerg1rl** [comment]
Kann ich gerne die Tage machen, wenn der Fehler erneut auftritt. Aktuell weiß ich leider nicht mehr, bei welcher bzw. nach welcher Codezeile er ausgelöst wird. //On Hold

**Comment by kevgk** [comment]
Sollte der Fehler wieder auftreten, einfach ein neues Issue auf machen.

**Comment by Pillowg1rl** [comment]
konnte den Fehler jetzt auf folgende Line festnageln:

`OldStr_Kundenliste2 := leya.listRows(TabelleReadout)`
`Loop, % OldStr_Kundenliste2.__affectedRows`
`OldStr_Kundenliste .= OldStr_Kundenliste2[A_Index-1] . "|"`

(Noch V2)
