### ISSUE TITLE
Error mit leya.get

### ISSUE THREAD

**Issue by xgamerg1rl** [kevgk/Leya#6]
Hey. (grade gelesen, dass man hier deutsch schreiben kann :D Macht das Problem erklären wesentlich einfacher ^^)

Folgender Code läuft leider nicht so rund wie gewollt...
``test_ := leya.get("Kunden","test","Firma")``
``msgbox % test.__error``
``msgbox % "The fullname of playerA is " . test.__affectedRows``
``msgbox % test``

Raus bekomme ich
__error : 0
__affectedRows : 1
test : (Leer)

``#include leya.ahk`` ist drin und das erstellen von Zeilen und das setzen von Werten funktioniert einwandfrei...
Könntest du dir das mal anschauen ? 

lg Michelle
PS: Hast du eventuell noch eine Kopie oder so von dem alten Wiki ? Da könnte man dann ja die Befehle rausziehen ;)

**Comment by kevgk** [comment]
Hi.
Du weist `test_` zu und verwendest anschliessend `test`, ohne den Unterstrich. Wobei du dann aber nicht __affectedRows: 1" raus bekommen solltest.

Entferne mal den Unterstrich und guck, was ob das dein Problem löst.

Hat die Datenbank einen Primarykey?

**Comment by xgamerg1rl** [comment]
Ja. die Mysql tabelle hat die erste Spalte als PrimaryKey gesetzt.
Habe den _ entfernt. Dann bekomme ich nur noch eine leere Meldung raus... :/
![SciTE_yBRPGYJWFW](https://user-images.githubusercontent.com/33255960/79773346-a4d0b980-8331-11ea-8b4a-73e9e310fcc0.png)
![SciTE_qcOh8mkGZA](https://user-images.githubusercontent.com/33255960/79773348-a5695000-8331-11ea-985b-31d3f3f809ee.png)

**Comment by kevgk** [comment]
Probier mal... 
```
test := leya.get("Kunden","test","Firma")
msgbox % test.Firma
```

**Comment by xgamerg1rl** [comment]
Oh okey.. das ist neu... Also mit test.Firma bekomme ich das gewünschte ergebnis raus.
sehr komisch...
Danke

**Comment by xgamerg1rl** [comment]
Hast du das alte Wiki von der Impov3d API ? Dann könnte ich mir da die Wert für die Befehle holen ;)

**Comment by kevgk** [comment]
Leider nein.

**Comment by xgamerg1rl** [comment]
achso:
und wo werden eher updates veröffentlicht ?
Hier oder https://freesoft.dev/program/10941071 ? :D Grade durch Zufall gefunden

**Comment by kevgk** [comment]
Ich maintaine ausschliesslich dieses Repository.

Den Link sehe ich gerade zum ersten Mal. Sieht aus wie ein Mirror, ist aber out of date.

Updates werden hier als erstes veröffentlicht. Zudem ist es sicherer, den Code hier direkt vom Author zu laden als von einem Drittanbieter, der möglicherweise, etwas am Code geändert hat.

**Comment by xgamerg1rl** [comment]
Alles klar. Solangsam werde ich auch mit deinem Coding bzw. Response Verarbeitungsmuster in der API warm und kann damit in AHK arbeiten :D Danke für die Hilfen ^^
