### ISSUE TITLE
leya.get Result Abfrage

### ISSUE THREAD

**Issue by xgamerg1rl** [kevgk/Leya#7]
huhu,

ist es gewollt, dass man bei der leya.get abfrage immernoch den Wert der Zeile hinzufügen muss?
also z.B.
``Readout := leya.get("Mitarbeiter","Max.Mustermann","Vorname")``
``Mitarbeitervorname_Readout := Readout.Vorname``

Wäre es nicht sinnvoller, dass man den Wert direkt unter der angegebenen Variable (in diesem Fall ``Readout``) abspeichert ? (Am besten dann natürlich direkt die Endvar (``Mitarbeitervorname_Readout``)

lg (PS: Hoffe es ist okey, wenn ich bei Fragen immer ein neues Issue aufmache ^^ oder soll ich das woanders posten ?)

**Comment by kevgk** [comment]
Das ist gewollt.

Zum einen muss jede Funktion ein Object wiedergeben, da neben den im Fall von `leya.get`, geforderten Daten, auch Werte wie __error und __affectedRows in der Antwort beinhaltet sein müssen.

Und zum Andern damit das Verhalten immer gleich ist, unabhängig davon, ob du 1 Spalte abfragst oder mehrere. Du kannst zB. auch `leya.get("Mitarbeiter","Max.Mustermann","Vorname, Nachname")` nutzen, um direkt Vor- und Nachname mit einer Anfrage zubekommen. mit `leya.get("Mitarbeiter","Max.Mustermann","*")` solltest du alle Spalten bekommen.


> Hoffe es ist okey, wenn ich bei Fragen immer ein neues Issue aufmache

Völlig in Ordnung.
