### ISSUE TITLE
getwhere (Value) nur mit Zahlen ?

### ISSUE THREAD

**Issue by xgamerg1rl** [kevgk/Leya#8]
Offenbar kann das Befehl getwhere nur mit Zahlen arbeiten.
Ich habe versucht, das ganze mit Wörtern zu verwenden, bekomme aber immer nur die Rückmeldung ``ï»¿<!--response="{"__error":-2,"__affectedRows":-1}"-->`` im Debug.
Bei Zahlen bekomme ich eine Rückmeldung. Aber der Parameter "=" kann ja auch einfach nur den Wert vergleichen oder ?

**Comment by kevgk** [comment]
Könntest du deinen Code dazu einmal posten?

**Comment by xgamerg1rl** [comment]
klar. Hoffe es ist soweit verständlich :D
https://p.ahkscript.org/?p=c3069a68

**Comment by kevgk** [comment]
War ein Bug in der API und ist jetzt gefixt. Du musst du API also einmal neu herunteladen.

**Comment by kevgk** [comment]
Und nochmal updaten, damit die getWhere Funktion auch Zahlen wieder richtig handled.

**Comment by xgamerg1rl** [comment]
hast du noch andere Sachen geändert ? Ich habe die aktuellste Version eingefügt, bekomme bei einem listRows keinen Wert mehr ausgegeben... :/ (https://p.ahkscript.org/?p=5159ee4c)
Nurnoch ein ``ï»¿`` (und natürlich darf die Typische Aussage nicht fehlen "Vorher hat's noch funktioniert" 🤣

**Comment by kevgk** [comment]
Bei mir funktioniert es. Hast du evtl. deine config.php überschrieben, so dass deine Zugangsdaten jetzt falsch sind?

**Comment by xgamerg1rl** [comment]
okey... versteh was der will... Plötzlich geht es wieder... hmm vielleicht hab ich irgendwo was falsch gesetzt.. naja danke :)
